# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-01 10:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Waifu2xData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('iphone_type', models.CharField(max_length=20)),
                ('run_time', models.CharField(max_length=100)),
                ('img_len', models.CharField(max_length=100)),
                ('img_wid', models.CharField(max_length=100)),
                ('img_area', models.CharField(max_length=100)),
            ],
        ),
    ]
